### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by p-larson** [hexagons/SwiftFX#1]
Hello,

When I am fetching the swift package, I am getting this resolution failure

`
package 'SwiftFX' is required using a revision-based requirement and it depends on local package 'LiveValues', which is not supported
`

I'm not sure if this is on my end or what. First time using the Swift Package manager, could be my fault.

**Comment by p-larson** [comment]
I see line 17-19 is commented out [here](https://github.com/hexagons/SwiftFX/issues),
perhaps it shouldn't be?

**Comment by heestand-xyz** [comment]
I merged your PR, Thanks!
